### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kongdd** [saedoquililongo/climQMBC#2]
I'd like to contribute to R version `climQMBC`. 
Could you tell me which license should I follow?

**Comment by saedoquililongo** [comment]
Hi Dongdong,

We appreciate your interest in collaborating to the `climQMBC` package. If you find a bug in the code or would like to suggest any new feature, you can help us by submitting an issue and outlining your proposal so that it can be discussed. This will allow us to better coordinate our efforts and prevent duplication of work.

We have not defined a license yet, but we will in an upcoming update of the repository.

Regards,
Sebastián Aedo
