### ISSUE TITLE
Does the package work with daily data?

### ISSUE THREAD

**Issue by Freestyleyang** [saedoquililongo/climQMBC#5]
Hi There,

Thank you for your amazing work in developing the "climQMBC" package! The "readme" page shows that "The climQMBC" package considers bias correction of **monthly and annual series** of variables whose changes are relative (precipitation) or absolute (temperature)."

I wonder if the package can be used to bias-correct daily time series of precipitation and temperature? Most climate models provide daily data and it would be great if the package works with daily data. Thanks.

**Comment by saedoquililongo** [comment]
Hej!

We have restricted or not implemented the methods for daily series because GCM results at daily time scale might not represent correctly trends at the local scale and the bias correction/adjustment process might induced additional and undesired biases. However, as the use of daily data is being used or mandated, we are working on enabling this capacity (along with other changes that we expect to be released during the first months of the year).

A way to enable daily datasets (which will be also included in the package) is to add another conditional (else if) with frq=='D' and I = 365 (assuming years of 365 days) in the formatQM function. Then, you would need to pass the frq argument with frq='D' when you call any of the QM methods to perform a daily correction.

Please comment if this solution worked for you or any other issue!

**Comment by Freestyleyang** [comment]
Hi There,

Thank you very much for your detailed explanation! Please keep me updated when you release the new package that works with daily rainfall and temperature data. 

It would be amazing to have a comprehensive package that focuses on different Quantile Mapping methods for bias correction. Thank you for your hard work.

**Comment by saedoquililongo** [comment]
Hej!

I am happy to announce that now the climQMBC package works with daily rainfall and temperature data!

The procedure considers a moving window for each day to be corrected to fit the probability distribution function and the projected changes. For precipitation it considers a secondary rainday threshold so that the number of raindays of the observed and modeled match in the reference period, and then the bias correction process focuses on the rainday values.

I hope this helps for future projects.
All the best!
